#!/usr/bin/env bash
# Regenerate privacy/index.md from the app repo's PRIVACY.md.
#
# PRIVACY.md is the single source of truth: it sits next to the code it
# describes, so it gets updated in the same commit as the behaviour it
# describes. This copy exists only because the app repo is private and the
# stores need a public URL. Never hand-edit privacy/index.md — run this.
set -euo pipefail

SRC="${1:-../jetlag-rn/PRIVACY.md}"
DEST="privacy/index.md"

if [ ! -f "$SRC" ]; then
  echo "no PRIVACY.md at: $SRC" >&2
  echo "usage: $0 [path/to/PRIVACY.md]" >&2
  exit 1
fi

{
  printf -- '---\n'
  printf -- 'layout: default\n'
  printf -- 'title: Privacy Policy\n'
  printf -- '# Generated by sync-privacy.sh from the app repo. Do not hand-edit.\n'
  printf -- '---\n\n'
  cat "$SRC"
} > "$DEST"

echo "wrote $DEST from $SRC"
